"""
Ansible Remediation Module - vulnerability SOAR (offline-first, dry-run default).

Phase 2 of LocalShield's DevSecOps direction. Where the firewall SOAR
(modules/response_engine.py) reacts to *network* threats, this reacts to
*vulnerabilities*: it turns the CVE findings stored by the vuln scanner into an
**Ansible playbook** that upgrades the affected packages across the affected
hosts — the fleet at the user's day job is Ansible-managed.

Design principles (consistent with the firewall SOAR):
- **Review-before-run.** Honors ``config.RESPONSE_DRY_RUN``: by default the
  playbook is generated, written to disk and audited, but ``ansible-playbook``
  is NEVER executed. The operator reviews the diff first.
- **Graceful degradation.** If ``ansible-playbook`` is absent, the playbook is
  still generated; execution is skipped with a warning. Nothing raises into the
  caller.
- **Reuse.** Findings come from ``db_manager.get_vulnerabilities``; the run is
  audited through the existing ``db_manager.record_action`` audit trail.
"""

import logging
import os
import re
import shutil
import subprocess
from datetime import datetime
from typing import Any, Dict, List, Optional

import yaml

import config
import db_manager

logger = logging.getLogger(__name__)

try:
    _DEFAULT_DRY_RUN = bool(getattr(config, "RESPONSE_DRY_RUN", False))
except Exception:  # config import should never fail, but stay defensive
    _DEFAULT_DRY_RUN = False

_PLAYBOOK_HEADER = (
    "# Generated by LocalShield vulnerability remediation (Phase 2).\n"
    "# Review before running. Map each play's `hosts` to your inventory, then:\n"
    "#   ansible-playbook <this-file>\n"
)


def _sanitize_host(target: str) -> str:
    """Turn a scan target (image name / path) into an inventory-safe host label."""
    return re.sub(r"[^A-Za-z0-9_.-]", "_", target).strip("_") or "all"


def generate_remediation_playbook(findings: List[Dict[str, Any]]) -> Optional[str]:
    """
    Build an Ansible playbook (YAML string) that patches every *fixable* finding
    (one with a known fixed_version). Findings are grouped by target into one
    play each, with one task per unique package (CVEs merged into the task name).
    Returns None when there is nothing fixable to do.
    """
    fixable = [f for f in findings if f.get("fixed_version")]
    if not fixable:
        return None

    # target -> {package -> {"fixed_version", "cves": set()}}
    by_target: Dict[str, Dict[str, Dict[str, Any]]] = {}
    for f in fixable:
        pkgs = by_target.setdefault(f["target"], {})
        entry = pkgs.setdefault(f["package"], {"fixed_version": f.get("fixed_version"), "cves": set()})
        entry["cves"].add(f["cve_id"])

    plays: List[Dict[str, Any]] = []
    for target in sorted(by_target):
        tasks: List[Dict[str, Any]] = []
        for package in sorted(by_target[target]):
            info = by_target[target][package]
            cves = ", ".join(sorted(info["cves"]))
            tasks.append(
                {
                    "name": f"Upgrade {package} to latest ({cves} fixed in {info['fixed_version']}+)",
                    "ansible.builtin.package": {"name": package, "state": "latest"},
                }
            )
        plays.append(
            {
                "name": f"LocalShield remediation for {target}",
                "hosts": _sanitize_host(target),
                "become": True,
                "tasks": tasks,
            }
        )

    return _PLAYBOOK_HEADER + yaml.safe_dump(plays, sort_keys=False, default_flow_style=False)


def _row_to_finding(row: tuple) -> Dict[str, Any]:
    """Map a db_manager.get_vulnerabilities() row to a finding dict."""
    # (id, cve_id, package, installed_version, fixed_version, severity,
    #  target, target_type, cvss, title, scan_time)
    return {
        "cve_id": row[1],
        "package": row[2],
        "installed_version": row[3],
        "fixed_version": row[4],
        "severity": row[5],
        "target": row[6],
    }


def playbook_for_db(db_path: Optional[str] = None) -> Optional[str]:
    """Generate a remediation playbook from the fixable findings in the DB."""
    rows = db_manager.get_vulnerabilities(fixable_only=True, db_path=db_path)
    return generate_remediation_playbook([_row_to_finding(r) for r in rows])


def _run_playbook(path: str) -> bool:
    """Execute a playbook with ansible-playbook. Never raises; False on any issue."""
    exe = getattr(config, "ANSIBLE_PLAYBOOK_PATH", "ansible-playbook")
    if shutil.which(exe) is None:
        logger.warning("⚠️  '%s' not found — playbook generated but NOT executed.", exe)
        return False
    try:
        proc = subprocess.run([exe, path], capture_output=True, text=True, timeout=1800)  # noqa: S603
        if proc.returncode == 0:
            logger.info("Ansible remediation applied via %s", path)
            return True
        logger.error("ansible-playbook failed (rc=%s): %s", proc.returncode, proc.stderr.strip())
        return False
    except Exception as e:
        logger.error("Error running ansible-playbook: %s", e, exc_info=True)
        return False


def remediate(
    dry_run: Optional[bool] = None,
    output_dir: Optional[str] = None,
    db_path: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Generate (and, only when explicitly not dry-run, apply) a remediation
    playbook for the fixable vulnerabilities in the DB. Always writes the
    playbook to disk and records an audit action. Returns a summary dict.
    """
    dry_run = _DEFAULT_DRY_RUN if dry_run is None else dry_run
    # str() keeps this concrete (getattr returns Any) for os.makedirs/os.path.join.
    output_dir = str(output_dir or getattr(config, "REMEDIATION_OUTPUT_DIR", "."))

    playbook = playbook_for_db(db_path=db_path)
    if not playbook:
        logger.info("No fixable vulnerabilities — nothing to remediate.")
        return {"playbook_path": None, "plays": 0, "executed": False, "dry_run": dry_run}

    os.makedirs(output_dir, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    path = os.path.join(output_dir, f"remediation_{ts}.yml")
    try:
        with open(path, "w", encoding="utf-8") as f:
            f.write(playbook)
    except Exception as e:
        logger.error("Could not write remediation playbook: %s", e, exc_info=True)
        return {"playbook_path": None, "plays": 0, "executed": False, "dry_run": dry_run}

    # YAML comments are ignored by the loader, so this counts the real plays.
    try:
        parsed = yaml.safe_load(playbook)
        plays = len(parsed) if isinstance(parsed, list) else 0
    except Exception:
        plays = 0
    db_manager.record_action(
        "generate_remediation_playbook",
        target=path,
        details=f"{plays} play(s); dry_run={dry_run}",
        db_path=db_path,
    )

    executed = False
    if dry_run:
        logger.warning("🧪 [DRY-RUN] Remediation playbook written to %s — NOT executed.", path)
    else:
        executed = _run_playbook(path)

    return {"playbook_path": path, "plays": plays, "executed": executed, "dry_run": dry_run}


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
    db_manager.init_db()
    print(remediate())
